name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "container/**"
      - ".github/**"

defaults:
  run:
    working-directory: container/

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }},
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
